### ISSUE TITLE
How to change the "Pulse output rate" and things related to it

### ISSUE THREAD

**Issue by TMHEINE** [gianfrdp/SDM120C#11]
Hi,

on the Eastron SDM120 Modbus the "Pulse Output 1" is configurable:

it can be set to represent total/Import/Export kWh or kVarh.
The pulse constant can be set to gernerate 1 pulse per: 0,001(Default)/0,01/0,1/1 kWh/kVarh
The pulse with can be set to 200/100/60ms

How can these settings be done with "sdm120c"?
see:
[SDM120CT-Modbus.pdf](https://github.com/gianfrdp/SDM120C/files/2309694/SDM120CT-Modbus.pdf)

**Comment by gianfrdp** [comment]
You have to change code, adding support for register 0xF910, adding a new command-line parameter to input new pulse value, adding a block of code where to invoke
`changeConfigHex(ctx, '0xF910', new_value, RESTART_FALSE);`

**Comment by gianfrdp** [comment]
Added new parameter -O for this issue, see https://github.com/gianfrdp/SDM120C/commit/2c3d88d6ee85927ca2139170fb0a443e272a33e2
