### ISSUE TITLE
Support for SDM630M and SDM530M

### ISSUE THREAD

**Issue by kobush** [gianfrdp/SDM120C#8]
Hello. Thank you for your great project.

Would it work with the three phase meters SDM630M or SDM530M? I'm thinking of installing it in my house as I have three phase connection. I found it via this discussion first http://openenergymonitor.org/emon/node/5743

Links to these meters:
http://www.aliexpress.com/item/SDM630-DC-Mutli-Function-Four-Module-Three-Phase-100A-Direct-Connection-Digital-Din-Rail-Power-Meter/936679409.html?spm=2114.12010108.100007.8.buESLy
http://www.aliexpress.com/item/SDM530Modbus-Three-Phase-Four-Wire-Din-Rail-Energy-Meter-with-RS485-Modbus-RTU-and-Pulse-Output/32407883775.html?spm=2114.10010108.100007.17.xkYKp4

**Comment by coolex** [comment]
+1

**Comment by mtrofimm** [comment]
:+1:

**Comment by grzech1983** [comment]
Hello,

I would also be interested in support for SDM630M. I've already ordered it and I will have it in about two weeks so I also could help with testing.

Thanks

**Comment by gianfrdp** [comment]
Hello, for the moment I have no plans to extend devices support.
I haven't a SDM630M, nor a SDM530M, so I couldn't test it. I only have a SDM120C and a SDM220.
For SDM320M, basic functions could already work, limited to 9600 baud speed.

**Comment by gianfrdp** [comment]
I forgot...
using my python script, could be easy to implement adding missing registers.
sdm120c.py
